modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="${mod_issues}"
license="${mod_license}"

[[mods]]
modId="create"
version="${file.jarVersion}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
logoFile="logo.png"
#credits=""
authors="${mod_author}"
description='''
${mod_description}
'''

[[dependencies.create]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="flywheel"
    mandatory=true
    versionRange="[0.6.10,0.6.11)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.create]]
    modId="catnip"
    mandatory=true
    versionRange="[0.6,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.create]]
    modId="ponder"
    mandatory=true
    versionRange="[0.6,)"
    ordering="AFTER"
    side="BOTH"
