modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="${mod_issues}"
license="${mod_license}"

[[mods]]
modId="create"
version="${file.jarVersion}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
logoFile="logo.png"
#credits=""
authors="${mod_author}"
description='''
${mod_description}
'''

[[dependencies.create]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="flywheel"
    mandatory=true
    versionRange="[0.6.9,0.6.10)"
    ordering="AFTER"
    side="CLIENT"
